### ISSUE TITLE
Google sheets does not show properly

### ISSUE THREAD

**Issue by williamjnrkdd** [Alex313031/Thorium#23]
The preview of the sheet on Thorium 102.0.4976.0 unstable
![image](https://user-images.githubusercontent.com/44339866/163037802-43e61ae4-707c-45fc-899d-4a3bd99b14a4.png)
The preview of the same sheet on Firefox just to show what the sheet should actually look like:
![image](https://user-images.githubusercontent.com/44339866/163038068-07b7aff7-3b0a-44a1-a098-3380b556ec39.png)
 This happens not only with this sheet but all other google sheets. It shows properly for just a few seconds then gets messed up like this.

**Comment by Alex313031** [comment]
@williamjnrkdd What OS are you using, and what DE? Can you send a link of a populated google sheet for me to test?
Thanks for using Thorium!

**Comment by williamjnrkdd** [comment]
I am using Parrot OS 4.11 . My apologies but what is the full meaning of DE?

**Comment by Alex313031** [comment]
@williamjnrkdd Desktop Environment
No need for apologies. And ok

**Comment by williamjnrkdd** [comment]
I am using MATE. I have accepted your access request.

**Comment by Alex313031** [comment]
@williamjnrkdd Hmmm it shows up fine for me and Im using the same version on crunchbangplusplus, a debian based distro just like parot os. Lemme ask, did you have chromium installed before installing thorium? Or are you using them side by side?

**Comment by williamjnrkdd** [comment]
@Alex313031 Actually I was using chromium before but had issues opening it. I tried to completely remove and reinstall but still had the same error. So i completely removed it, i think ( i did all i knew) and then i installed Thorium.

**Comment by Alex313031** [comment]
Ok, I would like you to do a sudo apt remove --purge chromium* and then sudo apt remove --purge thorium*
Then, go to ~/.config/ and move or rename the chromium folder and thorium folder (to back them up)
Then, install latest Thorium release from here, i.e. sudo dpkg -i thorium-browser.......etc. > https://github.com/Alex313031/Thorium/releases/tag/M102.0.4976.0

**Comment by williamjnrkdd** [comment]
Okay. I am testing. I would get back to you soon.

**Comment by williamjnrkdd** [comment]
I just finished and it is still the same.

**Comment by Alex313031** [comment]
Ok, do you have any flags set?

**Comment by Alex313031** [comment]
Wait nvm its using a fresh user profile dir. In that case, try going to chrome://flags/#ignore-gpu-blocklist and chrome://flags/#enable-container-queries and setting them both to enabled, then restart Thorium and test.

**Comment by williamjnrkdd** [comment]
I just tried that too and I still get that on google sheets. I also just noticed that every time i restart the browser I have to login again into my google account. I am only saying this if it may help in some way to identify where the problem is coming from.

**Comment by Alex313031** [comment]
Do you have google sync on?

**Comment by williamjnrkdd** [comment]
I tried that and it didn't work for me. I click on turn on sync. It leads me to a google sign in page. I login and I can see i have been logged in on youtube and all other google products but when i tap the account icon in thorium(where i tapped turn on sync), it still says turn on sync. @Alex313031

**Comment by Alex313031** [comment]
@williamjnrkdd Here add yourself to this google group as per the instructions in the previous release.
https://github.com/Alex313031/Thorium/releases/tag/M101.0.4949.0

**Comment by williamjnrkdd** [comment]
Oh I see. I have joined the group. @Alex313031

**Comment by Alex313031** [comment]
@williamjnrkdd Did that fix it?

**Comment by williamjnrkdd** [comment]
@Alex313031 yes it solved the problem with the sync but not the google sheets issue.

**Comment by Alex313031** [comment]
@williamjnrkdd That's so weird. I'll post here and let you know when I make a new linux release (soon) and then you can try that. Because otherwise IDK what the issue would be.

**Comment by williamjnrkdd** [comment]
I understand. Thank you for your help.

**Comment by Alex313031** [comment]
@williamjnrkdd Try the latest release and see if it still does this

**Comment by Alex313031** [comment]
@williamjnrkdd This should be fixed in latest release, because of patches and API keys fixes. Let me know how it goes.

**Comment by hakimzulkufli** [comment]
@Alex313031 Is the latest release M106.0.5212.0? I'm using the AppImage version. It's still happening to me. It was "fixed" after I first start this version but then it happened again. I have sync enabled as well as a custom theme installed. Could it be related to #47?

**Comment by Alex313031** [comment]
@hakimzulkufli Try this latest release which has a fix for #47 https://github.com/Alex313031/Thorium/releases/tag/M106.0.5237.0

**Comment by Alex313031** [comment]
@williamjnrkdd @yochananmarqos This should be fixed now.
